"""Migration 0014: location_pings monthly partitioning (S4).

Style-B tests: each creates a throwaway Postgres database and runs the real
Alembic chain from empty. Skipped when no Postgres test database is
configured (same convention as the 0013 tests).
"""

import asyncio
import os
import re
from datetime import UTC, datetime, timedelta
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from conftest import (
    create_test_campaign,
    create_test_campaign_assignment,
    create_test_driver_profile,
    create_test_organization,
    create_test_user,
    create_test_vehicle,
)
from sqlalchemy import CheckConstraint, UniqueConstraint, text
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import make_url
from sqlalchemy.exc import DBAPIError
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy.pool import NullPool

from alembic import command
from app.core.config import get_settings
from app.db.base import Base, PostGISGeometry
from app.models.user import UserRole
from app.services.data_lifecycle import add_months, month_start

REVISION_0014 = "0014_location_pings_partitioning"
REVISION_0013 = "0013_payout_v2_hourly_caps"

EXPECTED_CHECKS = {
    "ck_location_pings_sequence_number_non_negative",
    "ck_location_pings_latitude",
    "ck_location_pings_longitude",
    "ck_location_pings_accuracy_non_negative",
    "ck_location_pings_speed_non_negative",
    "ck_location_pings_heading_degrees",
    "ck_location_pings_altitude_m",
}
EXPECTED_INDEXES = {
    "ix_location_pings_trip_session_id",
    "ix_location_pings_trip_recorded_at",
    "ix_location_pings_batch_id",
    "ix_location_pings_geom",
}


def configured_postgres_url() -> str:
    database_url = os.environ.get("TEST_DATABASE_URL") or os.environ.get("DATABASE_URL")
    if database_url is None or not database_url.startswith("postgresql+asyncpg://"):
        pytest.skip("PostGIS test database is not configured")
    return database_url


async def create_database_from_url(database_url: str) -> str:
    source_url = make_url(database_url)
    database_name = f"test_0014_migration_{uuid4().hex}"
    maintenance_url = source_url.set(database="postgres")
    engine = create_async_engine(maintenance_url, isolation_level="AUTOCOMMIT", poolclass=NullPool)
    try:
        async with engine.connect() as connection:
            await connection.execute(text(f'CREATE DATABASE "{database_name}"'))
    finally:
        await engine.dispose()
    return source_url.set(database=database_name).render_as_string(hide_password=False)


async def drop_database(database_url: str) -> None:
    url = make_url(database_url)
    database_name = url.database
    if database_name is None:
        return
    maintenance_url = url.set(database="postgres")
    engine = create_async_engine(maintenance_url, isolation_level="AUTOCOMMIT", poolclass=NullPool)
    try:
        async with engine.connect() as connection:
            await connection.execute(
                text(
                    """
                    SELECT pg_terminate_backend(pid)
                    FROM pg_stat_activity
                    WHERE datname = :database_name AND pid <> pg_backend_pid()
                    """
                ),
                {"database_name": database_name},
            )
            await connection.execute(text(f'DROP DATABASE IF EXISTS "{database_name}"'))
    finally:
        await engine.dispose()


def upgrade_to(migration_url: str, revision: str, monkeypatch) -> None:
    monkeypatch.setenv("DATABASE_URL", migration_url)
    get_settings.cache_clear()
    command.upgrade(Config("alembic.ini"), revision)
    get_settings.cache_clear()


def downgrade_to(migration_url: str, revision: str, monkeypatch) -> None:
    monkeypatch.setenv("DATABASE_URL", migration_url)
    get_settings.cache_clear()
    command.downgrade(Config("alembic.ini"), revision)
    get_settings.cache_clear()


async def fetch_all(migration_url: str, query: str, params: dict | None = None) -> list:
    engine = create_async_engine(migration_url, poolclass=NullPool)
    try:
        async with engine.connect() as connection:
            result = await connection.execute(text(query), params or {})
            return list(result.all())
    finally:
        await engine.dispose()


async def execute_sql(migration_url: str, statement: str | tuple[str, ...]) -> None:
    engine = create_async_engine(migration_url, poolclass=NullPool)
    try:
        async with engine.begin() as connection:
            statements = (statement,) if isinstance(statement, str) else statement
            for item in statements:
                await connection.execute(text(item))
    finally:
        await engine.dispose()


def flatten_alembic_diffs(diffs: list) -> list[tuple]:
    flattened: list[tuple] = []
    for diff in diffs:
        if isinstance(diff, list):
            flattened.extend(flatten_alembic_diffs(diff))
        else:
            flattened.append(diff)
    return flattened


async def fetch_catalog_authority(migration_url: str) -> dict[str, dict]:
    table_names = sorted(Base.metadata.tables)
    engine = create_async_engine(migration_url, poolclass=NullPool)
    try:
        async with engine.begin() as connection:
            key_constraint_rows = (
                await connection.execute(
                    text(
                        """
                        SELECT table_class.relname AS table_name,
                           constraint_row.conname AS constraint_name,
                           constraint_row.contype::text AS constraint_type,
                           ARRAY(
                               SELECT attribute.attname
                               FROM unnest(constraint_row.conkey) WITH ORDINALITY
                                   AS key_column(attribute_number, ordinality)
                               JOIN pg_attribute attribute
                                 ON attribute.attrelid = table_class.oid
                                AND attribute.attnum = key_column.attribute_number
                               ORDER BY key_column.ordinality
                           ) AS key_column_names,
                           constraint_row.condeferrable AS deferrable,
                           constraint_row.condeferred AS initially_deferred,
                           ARRAY(
                               SELECT attribute.attname
                               FROM unnest(index_row.indkey) WITH ORDINALITY
                                   AS index_column(attribute_number, ordinality)
                               JOIN pg_attribute attribute
                                 ON attribute.attrelid = table_class.oid
                                AND attribute.attnum = index_column.attribute_number
                               WHERE index_column.ordinality > index_row.indnkeyatts
                               ORDER BY index_column.ordinality
                           ) AS included_column_names
                    FROM pg_constraint constraint_row
                    JOIN pg_class table_class ON table_class.oid = constraint_row.conrelid
                    JOIN pg_namespace namespace_row
                      ON namespace_row.oid = table_class.relnamespace
                    JOIN pg_index index_row
                      ON index_row.indexrelid = constraint_row.conindid
                    WHERE namespace_row.nspname = 'public'
                      AND constraint_row.contype IN ('p', 'u')
                      AND table_class.relname = ANY(CAST(:table_names AS text[]))
                        """
                    ),
                    {"table_names": table_names},
                )
            ).all()

            def catalog_signature(row) -> dict:
                return {
                    "key_columns": tuple(row.key_column_names),
                    "deferrable": row.deferrable,
                    "initially": (
                        "DEFERRED" if row.initially_deferred else "IMMEDIATE"
                    ),
                    "included_columns": tuple(row.included_column_names),
                }

            actual_primary_keys = {
                row.table_name: catalog_signature(row)
                for row in key_constraint_rows
                if row.constraint_type == "p"
            }
            actual_unique_constraints = {
                (row.table_name, row.constraint_name): catalog_signature(row)
                for row in key_constraint_rows
                if row.constraint_type == "u"
            }

            check_rows = await connection.execute(
                text(
                    """
                    SELECT table_class.relname AS table_name,
                           constraint_row.conname AS constraint_name,
                           pg_get_constraintdef(constraint_row.oid, false) AS definition
                    FROM pg_constraint constraint_row
                    JOIN pg_class table_class ON table_class.oid = constraint_row.conrelid
                    JOIN pg_namespace namespace_row
                      ON namespace_row.oid = table_class.relnamespace
                    WHERE namespace_row.nspname = 'public'
                      AND constraint_row.contype = 'c'
                      AND table_class.relname = ANY(CAST(:table_names AS text[]))
                    """
                ),
                {"table_names": table_names},
            )
            actual_checks = {
                (row.table_name, row.constraint_name): row.definition
                for row in check_rows
            }

            expected_checks: dict[tuple[str, str], str] = {}
            preparer = connection.dialect.identifier_preparer
            for index, metadata_table in enumerate(
                sorted(Base.metadata.tables.values(), key=lambda table: table.name)
            ):
                check_constraints = sorted(
                    (
                        constraint
                        for constraint in metadata_table.constraints
                        if isinstance(constraint, CheckConstraint)
                    ),
                    key=lambda constraint: constraint.name or "",
                )
                if not check_constraints:
                    continue
                assert all(constraint.name for constraint in check_constraints)
                temporary_table = f"r04_expected_checks_{index}"
                quoted_temporary_table = preparer.quote(temporary_table)
                quoted_public_table = (
                    f"{preparer.quote_schema('public')}."
                    f"{preparer.quote(metadata_table.name)}"
                )
                await connection.execute(
                    text(
                        f"CREATE TEMP TABLE {quoted_temporary_table} "
                        f"(LIKE {quoted_public_table} INCLUDING ALL) ON COMMIT DROP"
                    )
                )
                copied_checks = await connection.execute(
                    text(
                        """
                        SELECT conname
                        FROM pg_constraint
                        WHERE contype = 'c' AND conrelid = to_regclass(:table_name)
                        """
                    ),
                    {"table_name": f"pg_temp.{temporary_table}"},
                )
                for (constraint_name,) in copied_checks:
                    await connection.execute(
                        text(
                            f"ALTER TABLE {quoted_temporary_table} DROP CONSTRAINT "
                            f"{preparer.quote(constraint_name)}"
                        )
                    )
                for constraint in check_constraints:
                    expression = str(
                        constraint.sqltext.compile(
                            dialect=postgresql.dialect(),
                            compile_kwargs={"literal_binds": True},
                        )
                    )
                    await connection.execute(
                        text(
                            f"ALTER TABLE {quoted_temporary_table} ADD CONSTRAINT "
                            f"{preparer.quote(constraint.name)} CHECK ({expression})"
                        )
                    )
                expected_rows = await connection.execute(
                    text(
                        """
                        SELECT conname, pg_get_constraintdef(oid, false)
                        FROM pg_constraint
                        WHERE contype = 'c' AND conrelid = to_regclass(:table_name)
                        """
                    ),
                    {"table_name": f"pg_temp.{temporary_table}"},
                )
                expected_checks.update(
                    {
                        (metadata_table.name, constraint_name): definition
                        for constraint_name, definition in expected_rows
                    }
                )

            geometry_rows = await connection.execute(
                text(
                    """
                    SELECT table_class.relname AS table_name,
                           attribute.attname AS column_name,
                           postgis_typmod_type(attribute.atttypmod) AS subtype,
                           postgis_typmod_srid(attribute.atttypmod) AS srid
                    FROM pg_attribute attribute
                    JOIN pg_class table_class ON table_class.oid = attribute.attrelid
                    JOIN pg_namespace namespace_row
                      ON namespace_row.oid = table_class.relnamespace
                    JOIN pg_type type_row ON type_row.oid = attribute.atttypid
                    WHERE namespace_row.nspname = 'public'
                      AND type_row.typname = 'geometry'
                      AND attribute.attnum > 0
                      AND NOT attribute.attisdropped
                      AND table_class.relname = ANY(CAST(:table_names AS text[]))
                    """
                ),
                {"table_names": table_names},
            )
            actual_geometry = {
                (row.table_name, row.column_name): (row.subtype, row.srid)
                for row in geometry_rows
            }
    finally:
        await engine.dispose()

    def metadata_signature(constraint) -> dict:
        included_columns = constraint.dialect_options["postgresql"].get("include") or ()
        return {
            "key_columns": tuple(column.name for column in constraint.columns),
            "deferrable": (
                constraint.deferrable if constraint.deferrable is not None else False
            ),
            "initially": constraint.initially or "IMMEDIATE",
            "included_columns": tuple(
                column if isinstance(column, str) else column.name
                for column in included_columns
            ),
        }

    expected_primary_keys = {
        table.name: metadata_signature(table.primary_key)
        for table in Base.metadata.tables.values()
        if table.primary_key.columns
    }
    expected_unique_constraints = {
        (table.name, constraint.name): metadata_signature(constraint)
        for table in Base.metadata.tables.values()
        for constraint in table.constraints
        if isinstance(constraint, UniqueConstraint) and constraint.name is not None
    }
    actual_unique_constraints = {
        identity: signature
        for identity, signature in actual_unique_constraints.items()
        if identity in expected_unique_constraints
    }
    expected_geometry = {
        (table.name, column.name): (column.type.geometry_type, column.type.srid)
        for table in Base.metadata.tables.values()
        for column in table.columns
        if isinstance(column.type, PostGISGeometry)
    }
    return {
        "actual_primary_keys": actual_primary_keys,
        "expected_primary_keys": expected_primary_keys,
        "actual_unique_constraints": actual_unique_constraints,
        "expected_unique_constraints": expected_unique_constraints,
        "actual_checks": actual_checks,
        "expected_checks": expected_checks,
        "actual_geometry": actual_geometry,
        "expected_geometry": expected_geometry,
    }


def partition_rows(migration_url: str) -> list[tuple[str, str]]:
    return asyncio.run(
        fetch_all(
            migration_url,
            """
            SELECT child.relname, pg_get_expr(child.relpartbound, child.oid)
            FROM pg_inherits inh
            JOIN pg_class child ON child.oid = inh.inhrelid
            JOIN pg_class parent ON parent.oid = inh.inhparent
            WHERE parent.relname = 'location_pings'
            ORDER BY child.relname
            """,
        )
    )


def test_0014_migration_static_shape() -> None:
    migration = Path("alembic/versions/0014_location_pings_partitioning.py").read_text()
    assert f'revision: str = "{REVISION_0014}"' in migration
    assert f'down_revision: str | Sequence[str] | None = "{REVISION_0013}"' in migration
    assert "PARTITION BY RANGE (recorded_at)" in migration
    assert "MIGRATION_PREMAKE_MONTHS = 4" in migration
    # The initial premake horizon is frozen — never deployment config.
    assert "get_settings" not in migration
    assert "partition_premake_months" not in migration
    assert "os.environ" not in migration
    assert "DEFAULT PARTITION" not in migration.upper().replace("NO DEFAULT PARTITION", "")
    assert '"data_purge_audit"' in migration
    for name in EXPECTED_CHECKS | EXPECTED_INDEXES:
        assert name in migration
    for forbidden_table in ["notifications", "fraud_disputes", "payout_batches", "heatmaps"]:
        assert f'"{forbidden_table}"' not in migration


def test_data_purge_audit_is_database_immutable_and_appendable(monkeypatch) -> None:
    source_url = configured_postgres_url()
    migration_url = asyncio.run(create_database_from_url(source_url))

    async def exercise_immutability() -> None:
        engine = create_async_engine(migration_url, poolclass=NullPool)
        try:
            async with engine.connect() as connection:
                catalog = (
                    await connection.execute(
                        text(
                            """
                            SELECT trigger_row.tgname,
                                   trigger_row.tgenabled,
                                   trigger_row.tgtype,
                                   function_row.proname
                            FROM pg_trigger trigger_row
                            JOIN pg_proc function_row
                              ON function_row.oid = trigger_row.tgfoid
                            WHERE trigger_row.tgrelid = 'data_purge_audit'::regclass
                              AND NOT trigger_row.tgisinternal
                            """
                        )
                    )
                ).one()
                assert catalog == (
                    "data_purge_audit_immutable",
                    b"A",
                    58,
                    "reject_data_purge_audit_mutation",
                )
                await connection.rollback()

                await connection.execute(
                    text(
                        """
                        INSERT INTO data_purge_audit
                            (event, retention_months, job_run_id)
                        VALUES
                            ('batches_purged', 12, 'r07-original')
                        """
                    )
                )
                await connection.commit()

                mutations = (
                    "UPDATE data_purge_audit SET retention_months = 99",
                    "DELETE FROM data_purge_audit",
                    "TRUNCATE data_purge_audit",
                )
                for statement in mutations:
                    transaction = await connection.begin()
                    await connection.execute(text("SET LOCAL session_replication_role = replica"))
                    with pytest.raises(DBAPIError, match="data purge audit is immutable"):
                        await connection.execute(text(statement))
                    await transaction.rollback()

                    rows = (
                        await connection.execute(
                            text(
                                "SELECT job_run_id, retention_months "
                                "FROM data_purge_audit ORDER BY created_at, id"
                            )
                        )
                    ).all()
                    assert rows == [("r07-original", 12)]
                    await connection.rollback()

                await connection.execute(
                    text(
                        """
                        INSERT INTO data_purge_audit
                            (event, retention_months, job_run_id)
                        VALUES
                            ('batches_purged', 12, 'r07-appended')
                        """
                    )
                )
                await connection.commit()
                job_run_ids = (
                    await connection.execute(
                        text("SELECT job_run_id FROM data_purge_audit ORDER BY created_at, id")
                    )
                ).scalars()
                assert list(job_run_ids) == ["r07-original", "r07-appended"]
        finally:
            await engine.dispose()

    try:
        upgrade_to(migration_url, "head", monkeypatch)
        asyncio.run(exercise_immutability())
    finally:
        asyncio.run(drop_database(migration_url))


def test_empty_database_upgrade_downgrade_cycle(monkeypatch) -> None:
    source_url = configured_postgres_url()
    migration_url = asyncio.run(create_database_from_url(source_url))
    try:
        upgrade_to(migration_url, "head", monkeypatch)

        relkind = asyncio.run(
            fetch_all(
                migration_url,
                "SELECT relkind::text FROM pg_class WHERE relname = 'location_pings'",
            )
        )
        assert relkind == [("p",)]

        rows = partition_rows(migration_url)
        names = [name for name, _ in rows]
        assert "location_pings_legacy" not in names
        assert all(re.fullmatch(r"location_pings_p\d{4}_\d{2}", name) for name in names)
        assert not any("DEFAULT" in bound for _, bound in rows)
        # Empty branch covers three prior months (rich-seed history depth is
        # 56 days) through the frozen 4-month horizon.
        now_month = month_start(datetime.now(UTC))
        expected = {
            f"location_pings_p{add_months(now_month, offset).strftime('%Y_%m')}"
            for offset in range(-3, 5)
        }
        assert set(names) == expected

        constraints = {
            row[0]
            for row in asyncio.run(
                fetch_all(
                    migration_url,
                    """
                    SELECT conname FROM pg_constraint
                    WHERE conrelid = 'location_pings'::regclass
                    """,
                )
            )
        }
        assert EXPECTED_CHECKS <= constraints
        assert "location_pings_pkey" in constraints
        assert {"location_pings_trip_session_id_fkey", "location_pings_batch_id_fkey"} <= (
            constraints
        )
        pk_cols = asyncio.run(
            fetch_all(
                migration_url,
                """
                SELECT a.attname
                FROM pg_index i
                JOIN pg_attribute a ON a.attrelid = i.indrelid
                    AND a.attnum = ANY(i.indkey)
                WHERE i.indrelid = 'location_pings'::regclass AND i.indisprimary
                ORDER BY a.attname
                """,
            )
        )
        assert {row[0] for row in pk_cols} == {"id", "recorded_at"}

        indexes = {
            row[0]
            for row in asyncio.run(
                fetch_all(
                    migration_url,
                    "SELECT indexname FROM pg_indexes WHERE tablename = 'location_pings'",
                )
            )
        }
        assert EXPECTED_INDEXES <= indexes

        purge_indexes = {
            row[0]
            for row in asyncio.run(
                fetch_all(
                    migration_url,
                    "SELECT indexname FROM pg_indexes WHERE tablename = 'data_purge_audit'",
                )
            )
        }
        assert {"uq_data_purge_audit_dropped", "ix_data_purge_audit_partition_created_at"} <= (
            purge_indexes
        )

        downgrade_to(migration_url, REVISION_0013, monkeypatch)
        relkind = asyncio.run(
            fetch_all(
                migration_url,
                "SELECT relkind::text FROM pg_class WHERE relname = 'location_pings'",
            )
        )
        assert relkind == [("r",)]
        tables = asyncio.run(
            fetch_all(
                migration_url,
                "SELECT 1 FROM information_schema.tables WHERE table_name = 'data_purge_audit'",
            )
        )
        assert tables == []

        upgrade_to(migration_url, "head", monkeypatch)
    finally:
        asyncio.run(drop_database(migration_url))


def seed_ping_graph(migration_url: str) -> dict:
    """Build the minimal FK graph at revision 0013 and insert pings across
    three UTC months, including a batch straddling two months."""
    engine = create_async_engine(migration_url, poolclass=NullPool)
    sessionmaker = async_sessionmaker(engine, expire_on_commit=False)
    now = datetime.now(UTC)
    months = [add_months(month_start(now), -2), add_months(month_start(now), -1), month_start(now)]

    admin = create_test_user(sessionmaker, email="mig-admin@example.com")
    advertiser = create_test_user(
        sessionmaker, email="mig-advertiser@example.com", role=UserRole.ADVERTISER
    )
    driver = create_test_user(sessionmaker, email="mig-driver@example.com", role=UserRole.DRIVER)
    organization, _ = create_test_organization(
        sessionmaker, owner_user_id=advertiser.id, legacy_schema=True
    )
    campaign = create_test_campaign(
        sessionmaker, organization_id=organization.id, created_by_user_id=advertiser.id
    )
    profile = create_test_driver_profile(sessionmaker, user_id=driver.id)
    vehicle = create_test_vehicle(sessionmaker, driver_profile_id=profile.id)
    assignment = create_test_campaign_assignment(
        sessionmaker,
        campaign_id=campaign.id,
        driver_profile_id=profile.id,
        vehicle_id=vehicle.id,
        assigned_by_user_id=admin.id,
        legacy_schema=True,
    )
    # Raw SQL: this seed runs at revision 0013, before the 0016 seal columns
    # exist — the current ORM model would INSERT columns the old schema lacks.
    trip_id = uuid4()

    async def add_trip() -> None:
        async with sessionmaker() as session:
            await session.execute(
                text(
                    "INSERT INTO trip_sessions (id, assignment_id, campaign_id,"
                    " driver_profile_id, vehicle_id, started_by_user_id, status,"
                    " started_at, metadata)"
                    " VALUES (:id, :assignment_id, :campaign_id, :driver_profile_id,"
                    " :vehicle_id, :started_by_user_id, 'active', :started_at, '{}')"
                ),
                {
                    "id": trip_id,
                    "assignment_id": assignment.id,
                    "campaign_id": campaign.id,
                    "driver_profile_id": profile.id,
                    "vehicle_id": vehicle.id,
                    "started_by_user_id": driver.id,
                    "started_at": months[0] + timedelta(hours=8),
                },
            )
            await session.commit()

    asyncio.run(add_trip())

    async def add_batch(key: str, recorded_ats: list[datetime]) -> tuple[str, list[str]]:
        batch_id = uuid4()
        ping_ids = [uuid4() for _ in recorded_ats]
        async with sessionmaker() as session:
            await session.execute(
                text(
                    "INSERT INTO location_ping_batches"
                    " (id, trip_session_id, idempotency_key, payload_hash,"
                    "  pings_accepted, received_at, metadata)"
                    " VALUES (:id, :trip_session_id, :idempotency_key, :payload_hash,"
                    "         :pings_accepted, :received_at, '{}'::jsonb)"
                ),
                {
                    "id": batch_id,
                    "trip_session_id": trip_id,
                    "idempotency_key": key,
                    "payload_hash": f"hash-{key}",
                    "pings_accepted": len(recorded_ats),
                    "received_at": recorded_ats[0],
                },
            )
            for ping_id, (sequence, recorded_at) in zip(
                ping_ids, enumerate(recorded_ats), strict=True
            ):
                await session.execute(
                    text(
                        "INSERT INTO location_pings"
                        " (id, trip_session_id, batch_id, recorded_at, received_at,"
                        "  sequence_number, latitude, longitude, accuracy_m, geom, metadata)"
                        " VALUES (:id, :trip_session_id, :batch_id, :recorded_at, :received_at,"
                        "         :sequence_number, 6.45, 3.39, 10,"
                        "         ST_SetSRID(ST_MakePoint(3.39, 6.45), 4326), '{}'::jsonb)"
                    ),
                    {
                        "id": ping_id,
                        "trip_session_id": trip_id,
                        "batch_id": batch_id,
                        "recorded_at": recorded_at,
                        "received_at": recorded_at,
                        "sequence_number": sequence,
                    },
                )
            await session.commit()
            return str(batch_id), [str(ping_id) for ping_id in ping_ids]

    batches = {}
    batches["oldest"] = asyncio.run(
        add_batch("batch-oldest", [months[0] + timedelta(hours=9, minutes=m) for m in range(3)])
    )
    batches["middle"] = asyncio.run(
        add_batch("batch-middle", [months[1] + timedelta(hours=9, minutes=m) for m in range(3)])
    )
    # Straddles the previous and current month.
    batches["straddling"] = asyncio.run(
        add_batch(
            "batch-straddling",
            [months[2] - timedelta(minutes=1), months[2] + timedelta(minutes=1)],
        )
    )
    asyncio.run(engine.dispose())
    return {"trip_id": str(trip_id), "batches": batches, "months": months}


def test_seeded_conversion_preserves_rows_and_routes_inserts(monkeypatch) -> None:
    source_url = configured_postgres_url()
    migration_url = asyncio.run(create_database_from_url(source_url))
    try:
        upgrade_to(migration_url, REVISION_0013, monkeypatch)
        seeded = seed_ping_graph(migration_url)
        all_ping_ids = sorted(
            ping_id for _, ping_ids in seeded["batches"].values() for ping_id in ping_ids
        )

        upgrade_to(migration_url, "head", monkeypatch)

        rows = partition_rows(migration_url)
        names = [name for name, _ in rows]
        assert "location_pings_legacy" in names
        assert not any("DEFAULT" in bound for _, bound in rows)

        surviving = asyncio.run(
            fetch_all(
                migration_url,
                "SELECT id::text, tableoid::regclass::text FROM location_pings ORDER BY id::text",
            )
        )
        assert sorted(row[0] for row in surviving) == all_ping_ids
        # Every pre-existing row lives in the legacy partition (it owns the
        # whole historical range including the current month).
        assert {row[1] for row in surviving} == {"location_pings_legacy"}

        # FK integrity survived: every ping still joins its batch and trip.
        orphans = asyncio.run(
            fetch_all(
                migration_url,
                """
                SELECT count(*) FROM location_pings p
                WHERE NOT EXISTS (SELECT 1 FROM location_ping_batches b WHERE b.id = p.batch_id)
                   OR NOT EXISTS (SELECT 1 FROM trip_sessions t WHERE t.id = p.trip_session_id)
                """,
            )
        )
        assert orphans == [(0,)]

        # UTC month-boundary routing of new inserts: current-month rows land
        # in legacy; rows at and after the next boundary land in the premade
        # monthly partition.
        next_month = add_months(month_start(datetime.now(UTC)), 1)
        batch_id = seeded["batches"]["straddling"][0]
        checks = [
            (datetime.now(UTC), "location_pings_legacy"),
            (next_month - timedelta(microseconds=1), "location_pings_legacy"),
            (next_month, f"location_pings_p{next_month.strftime('%Y_%m')}"),
        ]

        async def insert_and_locate(recorded_at: datetime) -> str:
            engine = create_async_engine(migration_url, poolclass=NullPool)
            try:
                async with engine.begin() as connection:
                    result = await connection.execute(
                        text(
                            """
                            INSERT INTO location_pings
                                (trip_session_id, batch_id, recorded_at, received_at,
                                 latitude, longitude, geom, metadata)
                            VALUES
                                (:trip_id, :batch_id, :recorded_at, :recorded_at,
                                 6.45, 3.39,
                                 ST_SetSRID(ST_MakePoint(3.39, 6.45), 4326), '{}'::jsonb)
                            RETURNING tableoid::regclass::text
                            """
                        ),
                        {
                            "trip_id": seeded["trip_id"],
                            "batch_id": batch_id,
                            "recorded_at": recorded_at,
                        },
                    )
                    return result.scalar_one()
            finally:
                await engine.dispose()

        for recorded_at, expected_partition in checks:
            assert asyncio.run(insert_and_locate(recorded_at)) == expected_partition

        expected_total = len(all_ping_ids) + len(checks)
        count = asyncio.run(fetch_all(migration_url, "SELECT count(*) FROM location_pings"))
        assert count == [(expected_total,)]

        # Downgrade restores the unpartitioned shape losslessly.
        downgrade_to(migration_url, REVISION_0013, monkeypatch)
        count = asyncio.run(fetch_all(migration_url, "SELECT count(*) FROM location_pings"))
        assert count == [(expected_total,)]
        pk_cols = asyncio.run(
            fetch_all(
                migration_url,
                """
                SELECT a.attname FROM pg_index i
                JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
                WHERE i.indrelid = 'location_pings'::regclass AND i.indisprimary
                """,
            )
        )
        assert {row[0] for row in pk_cols} == {"id"}

        upgrade_to(migration_url, "head", monkeypatch)
        count = asyncio.run(fetch_all(migration_url, "SELECT count(*) FROM location_pings"))
        assert count == [(expected_total,)]
    finally:
        asyncio.run(drop_database(migration_url))


def test_canonical_alembic_check_is_empty_at_exact_head(monkeypatch) -> None:
    source_url = configured_postgres_url()
    migration_url = asyncio.run(create_database_from_url(source_url))
    try:
        upgrade_to(migration_url, "head", monkeypatch)
        command.check(Config("alembic.ini"))
    finally:
        asyncio.run(drop_database(migration_url))


def test_canonical_alembic_check_detects_visible_schema_drift(monkeypatch) -> None:
    source_url = configured_postgres_url()
    migration_url = asyncio.run(create_database_from_url(source_url))
    mutations = [
        (
            "index",
            "DROP INDEX ix_vehicles_status",
            "CREATE INDEX ix_vehicles_status ON vehicles (status)",
            lambda diff: diff[0] == "add_index" and diff[1].name == "ix_vehicles_status",
        ),
        (
            "unique constraint",
            "ALTER TABLE users DROP CONSTRAINT uq_users_email",
            "ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email)",
            lambda diff: diff[0] == "add_constraint"
            and diff[1].name == "uq_users_email",
        ),
        (
            "foreign key",
            "ALTER TABLE vehicles DROP CONSTRAINT vehicles_driver_profile_id_fkey",
            "ALTER TABLE vehicles ADD CONSTRAINT vehicles_driver_profile_id_fkey "
            "FOREIGN KEY (driver_profile_id) REFERENCES driver_profiles(id) ON DELETE CASCADE",
            lambda diff: diff[0] == "add_fk"
            and diff[1].table.name == "vehicles"
            and tuple(diff[1].columns.keys()) == ("driver_profile_id",),
        ),
        (
            "column type",
            "ALTER TABLE users ALTER COLUMN full_name TYPE text",
            "ALTER TABLE users ALTER COLUMN full_name TYPE varchar(255)",
            lambda diff: diff[0] == "modify_type"
            and diff[2:4] == ("users", "full_name"),
        ),
        (
            "JSON subtype",
            (
                "ALTER TABLE campaigns ALTER COLUMN metadata DROP DEFAULT",
                "ALTER TABLE campaigns ALTER COLUMN metadata "
                "TYPE json USING metadata::json",
                "ALTER TABLE campaigns ALTER COLUMN metadata SET DEFAULT '{}'::json",
            ),
            (
                "ALTER TABLE campaigns ALTER COLUMN metadata DROP DEFAULT",
                "ALTER TABLE campaigns ALTER COLUMN metadata "
                "TYPE jsonb USING metadata::jsonb",
                "ALTER TABLE campaigns ALTER COLUMN metadata SET DEFAULT '{}'::jsonb",
            ),
            lambda diff: diff[0] == "modify_type"
            and diff[2:4] == ("campaigns", "metadata"),
        ),
        (
            "server default",
            "ALTER TABLE users ALTER COLUMN must_change_password SET DEFAULT true",
            "ALTER TABLE users ALTER COLUMN must_change_password SET DEFAULT false",
            lambda diff: diff[0] == "modify_default"
            and diff[2:4] == ("users", "must_change_password"),
        ),
        (
            "JSON server default",
            "ALTER TABLE assignment_activity_flags ALTER COLUMN evidence "
            "SET DEFAULT '{\"drift\": true}'::json",
            "ALTER TABLE assignment_activity_flags ALTER COLUMN evidence "
            "SET DEFAULT '{}'::json",
            lambda diff: diff[0] == "modify_default"
            and diff[2:4] == ("assignment_activity_flags", "evidence"),
        ),
    ]
    try:
        upgrade_to(migration_url, "head", monkeypatch)
        for label, apply_statement, restore_statement, detects_mutation in mutations:
            asyncio.run(execute_sql(migration_url, apply_statement))
            try:
                with pytest.raises(AutogenerateDiffsDetected) as exc_info:
                    command.check(Config("alembic.ini"))
                assert any(
                    detects_mutation(diff)
                    for diff in flatten_alembic_diffs(exc_info.value.diffs)
                ), f"canonical Alembic check did not report the {label} mutation"
            finally:
                asyncio.run(execute_sql(migration_url, restore_statement))
            command.check(Config("alembic.ini"))
    finally:
        asyncio.run(drop_database(migration_url))


def test_exact_head_catalog_matches_pk_unique_check_and_geometry_metadata(monkeypatch) -> None:
    source_url = configured_postgres_url()
    migration_url = asyncio.run(create_database_from_url(source_url))
    mutations = [
        (
            "primary_keys",
            "audit_events",
            "ALTER TABLE audit_events DROP CONSTRAINT audit_events_pkey",
            "ALTER TABLE audit_events ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id)",
        ),
        (
            "primary_keys",
            "audit_events",
            (
                "ALTER TABLE audit_events DROP CONSTRAINT audit_events_pkey",
                "ALTER TABLE audit_events ADD CONSTRAINT audit_events_pkey "
                "PRIMARY KEY (id) DEFERRABLE INITIALLY DEFERRED",
            ),
            (
                "ALTER TABLE audit_events DROP CONSTRAINT audit_events_pkey",
                "ALTER TABLE audit_events ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id)",
            ),
        ),
        (
            "primary_keys",
            "audit_events",
            (
                "ALTER TABLE audit_events DROP CONSTRAINT audit_events_pkey",
                "ALTER TABLE audit_events ADD CONSTRAINT audit_events_pkey "
                "PRIMARY KEY (id) INCLUDE (actor_user_id)",
            ),
            (
                "ALTER TABLE audit_events DROP CONSTRAINT audit_events_pkey",
                "ALTER TABLE audit_events ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id)",
            ),
        ),
        (
            "unique_constraints",
            ("users", "uq_users_email"),
            (
                "ALTER TABLE users DROP CONSTRAINT uq_users_email",
                "ALTER TABLE users ADD CONSTRAINT uq_users_email "
                "UNIQUE (email) DEFERRABLE INITIALLY DEFERRED",
            ),
            (
                "ALTER TABLE users DROP CONSTRAINT uq_users_email",
                "ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email)",
            ),
        ),
        (
            "unique_constraints",
            ("users", "uq_users_email"),
            (
                "ALTER TABLE users DROP CONSTRAINT uq_users_email",
                "ALTER TABLE users ADD CONSTRAINT uq_users_email "
                "UNIQUE (email) INCLUDE (full_name)",
            ),
            (
                "ALTER TABLE users DROP CONSTRAINT uq_users_email",
                "ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email)",
            ),
        ),
        (
            "checks",
            ("users", "ck_users_role"),
            (
                "ALTER TABLE users DROP CONSTRAINT ck_users_role",
                "ALTER TABLE users ADD CONSTRAINT ck_users_role "
                "CHECK (role IN ('admin', 'advertiser', 'driver', 'invalid'))",
            ),
            (
                "ALTER TABLE users DROP CONSTRAINT ck_users_role",
                "ALTER TABLE users ADD CONSTRAINT ck_users_role "
                "CHECK (role IN ('admin', 'advertiser', 'driver'))",
            ),
        ),
        (
            "geometry",
            ("campaign_zones", "geom"),
            "ALTER TABLE campaign_zones ALTER COLUMN geom "
            "TYPE geometry(Polygon,4326) USING ST_GeometryN(geom, 1)",
            "ALTER TABLE campaign_zones ALTER COLUMN geom "
            "TYPE geometry(MultiPolygon,4326) USING ST_Multi(geom)",
        ),
        (
            "geometry",
            ("campaign_zones", "geom"),
            "ALTER TABLE campaign_zones ALTER COLUMN geom "
            "TYPE geometry(MultiPolygon,3857) USING ST_Transform(geom, 3857)",
            "ALTER TABLE campaign_zones ALTER COLUMN geom "
            "TYPE geometry(MultiPolygon,4326) USING ST_Transform(geom, 4326)",
        ),
    ]
    try:
        upgrade_to(migration_url, "head", monkeypatch)
        baseline = asyncio.run(fetch_catalog_authority(migration_url))
        assert baseline["actual_primary_keys"] == baseline["expected_primary_keys"]
        assert baseline["actual_unique_constraints"] == baseline["expected_unique_constraints"]
        assert baseline["expected_primary_keys"]["audit_events"] == {
            "key_columns": ("id",),
            "deferrable": False,
            "initially": "IMMEDIATE",
            "included_columns": (),
        }
        assert baseline["expected_unique_constraints"][("users", "uq_users_email")] == {
            "key_columns": ("email",),
            "deferrable": False,
            "initially": "IMMEDIATE",
            "included_columns": (),
        }
        assert baseline["actual_checks"] == baseline["expected_checks"]
        assert baseline["expected_geometry"] == {
            ("campaign_zones", "geom"): ("MultiPolygon", 4326),
            ("location_pings", "geom"): ("Point", 4326),
        }
        assert baseline["actual_geometry"] == baseline["expected_geometry"]

        for authority, identifier, apply_statement, restore_statement in mutations:
            asyncio.run(execute_sql(migration_url, apply_statement))
            try:
                mutated = asyncio.run(fetch_catalog_authority(migration_url))
                assert mutated[f"actual_{authority}"].get(identifier) != mutated[
                    f"expected_{authority}"
                ].get(identifier)
            finally:
                asyncio.run(execute_sql(migration_url, restore_statement))
            restored = asyncio.run(fetch_catalog_authority(migration_url))
            assert restored[f"actual_{authority}"] == restored[f"expected_{authority}"]
    finally:
        asyncio.run(drop_database(migration_url))
